# SPDX-License-Identifier: Apache-2.0
# Container image release (GHCR) + optional SBOM / SLSA via shared rune-ci workflow.
# Triggers only on version tags (v*). PyPI publishing is separate: publish-pypi.yml.
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    uses: lpasquali/rune-ci/.github/workflows/release.yml@9f939b2c28317b6f55c1913c6a6485bd91e1bda5 # main
    with:
      image-name: "rune-audit"
      generate-sbom: true
      slsa-attestation: true
    secrets: inherit
